# Generated by Django 2.2.5 on 2019-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('name', models.CharField(help_text='Name of setting, must be unique.', max_length=64, primary_key=True, serialize=False)),
                ('action_int', models.IntegerField(blank=True, help_text='The setting integer. NOTE: If only using integer, check use_integer box and uncheck use_string!', null=True)),
                ('action_str', models.TextField(blank=True, help_text='The setting string. (json: {"key:"val","key2":2}) NOTE: If only using string, check use_string box and uncheck use_integer!', null=True)),
                ('use_integer', models.BooleanField(default=True, help_text='Use integer part of this setting?')),
                ('use_string', models.BooleanField(default=False, help_text='Use string part of this setting?')),
                ('description', models.CharField(blank=True, help_text='Description of setting.', max_length=200, null=True)),
                ('game_name', models.CharField(default='testapp', max_length=12)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
